module.exports =  {
    styles: [
        "./assets/src/scss/themes/light.scss" ,
        "./assets/src/scss/themes/0.scss" ,
        "./assets/src/scss/themes/1.scss" ,
        "./assets/src/scss/themes/2.scss" ,
        "./assets/src/scss/themes/3.scss" ,
        "./assets/src/scss/themes/4.scss" ,
        "./assets/src/scss/themes/5.scss" ,
        "./assets/src/scss/themes/6.scss" ,
        "./assets/src/scss/themes/7.scss" ,
        "./assets/src/scss/themes/8.scss" ,
        "./assets/src/scss/themes/9.scss" ,
        "./assets/src/scss/themes/10.scss" ,
        "./assets/src/scss/themes/11.scss" ,
        "./assets/src/scss/themes/12.scss" ,
        "./assets/src/scss/themes/13.scss" ,
        "./assets/src/scss/themes/14.scss" ,
        "./assets/src/scss/themes/15.scss" ,
        "./assets/src/scss/themes/16.scss" ,
        "./assets/src/scss/themes/17.scss" ,
        "./assets/src/scss/themes/18.scss" ,
        "./assets/src/scss/themes/19.scss" ,
        "./assets/src/scss/themes/20.scss" ,
        "./assets/src/scss/themes/21.scss" ,
        "./assets/src/scss/themes/22.scss" ,
        "./assets/src/scss/themes/23.scss" ,
        "./assets/src/scss/themes/24.scss" ,
        "./assets/src/scss/themes/25.scss" ,
        "./assets/src/scss/themes/26.scss" ,
        "./assets/src/scss/themes/27.scss" ,
        "./assets/src/scss/themes/28.scss" ,
        "./assets/src/scss/themes/29.scss" ,
        "./assets/src/scss/themes/30.scss" ,
        "./assets/src/scss/themes/31.scss" ,
        "./assets/src/scss/themes/32.scss" ,
        "./assets/src/scss/themes/33.scss" ,
        "./assets/src/scss/themes/34.scss" ,
        "./assets/src/scss/themes/35.scss" ,
        "./assets/src/scss/themes/36.scss" ,
        "./assets/src/scss/themes/37.scss" ,
        "./assets/src/scss/themes/38.scss" ,
        "./assets/src/scss/themes/39.scss" ,
        "./assets/src/scss/themes/40.scss"
    ],
};
